package com.mall.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PmsProduct implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.brand_id
     *
     * @mbggenerated
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_category_id
     *
     * @mbggenerated
     */
    private Long productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.feight_template_id
     *
     * @mbggenerated
     */
    private Long feightTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_attribute_category_id
     *
     * @mbggenerated
     */
    private Long productAttributeCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_sn
     *
     * @mbggenerated
     */
    private String productSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.delete_status
     *
     * @mbggenerated
     */
    private Integer deleteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.publish_status
     *
     * @mbggenerated
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.new_status
     *
     * @mbggenerated
     */
    private Integer newStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.recommand_status
     *
     * @mbggenerated
     */
    private Integer recommandStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.verify_status
     *
     * @mbggenerated
     */
    private Integer verifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.sale
     *
     * @mbggenerated
     */
    private Integer sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_price
     *
     * @mbggenerated
     */
    private BigDecimal promotionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.gift_growth
     *
     * @mbggenerated
     */
    private Integer giftGrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.gift_point
     *
     * @mbggenerated
     */
    private Integer giftPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.use_point_limit
     *
     * @mbggenerated
     */
    private Integer usePointLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.sub_title
     *
     * @mbggenerated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.original_price
     *
     * @mbggenerated
     */
    private BigDecimal originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.low_stock
     *
     * @mbggenerated
     */
    private Integer lowStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.weight
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.preview_status
     *
     * @mbggenerated
     */
    private Integer previewStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.service_ids
     *
     * @mbggenerated
     */
    private String serviceIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.album_pics
     *
     * @mbggenerated
     */
    private String albumPics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_title
     *
     * @mbggenerated
     */
    private String detailTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_start_time
     *
     * @mbggenerated
     */
    private Date promotionStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_end_time
     *
     * @mbggenerated
     */
    private Date promotionEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_per_limit
     *
     * @mbggenerated
     */
    private Integer promotionPerLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_type
     *
     * @mbggenerated
     */
    private Integer promotionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_category_name
     *
     * @mbggenerated
     */
    private String productCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_desc
     *
     * @mbggenerated
     */
    private String detailDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_html
     *
     * @mbggenerated
     */
    private String detailHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_mobile_html
     *
     * @mbggenerated
     */
    private String detailMobileHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    private Long userId;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.id
     *
     * @return the value of pms_product.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.id
     *
     * @param id the value for pms_product.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.brand_id
     *
     * @return the value of pms_product.brand_id
     *
     * @mbggenerated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.brand_id
     *
     * @param brandId the value for pms_product.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.product_category_id
     *
     * @return the value of pms_product.product_category_id
     *
     * @mbggenerated
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.product_category_id
     *
     * @param productCategoryId the value for pms_product.product_category_id
     *
     * @mbggenerated
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.feight_template_id
     *
     * @return the value of pms_product.feight_template_id
     *
     * @mbggenerated
     */
    public Long getFeightTemplateId() {
        return feightTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.feight_template_id
     *
     * @param feightTemplateId the value for pms_product.feight_template_id
     *
     * @mbggenerated
     */
    public void setFeightTemplateId(Long feightTemplateId) {
        this.feightTemplateId = feightTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.product_attribute_category_id
     *
     * @return the value of pms_product.product_attribute_category_id
     *
     * @mbggenerated
     */
    public Long getProductAttributeCategoryId() {
        return productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.product_attribute_category_id
     *
     * @param productAttributeCategoryId the value for pms_product.product_attribute_category_id
     *
     * @mbggenerated
     */
    public void setProductAttributeCategoryId(Long productAttributeCategoryId) {
        this.productAttributeCategoryId = productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.name
     *
     * @return the value of pms_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.name
     *
     * @param name the value for pms_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.pic
     *
     * @return the value of pms_product.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.pic
     *
     * @param pic the value for pms_product.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.product_sn
     *
     * @return the value of pms_product.product_sn
     *
     * @mbggenerated
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.product_sn
     *
     * @param productSn the value for pms_product.product_sn
     *
     * @mbggenerated
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn == null ? null : productSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.delete_status
     *
     * @return the value of pms_product.delete_status
     *
     * @mbggenerated
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.delete_status
     *
     * @param deleteStatus the value for pms_product.delete_status
     *
     * @mbggenerated
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.publish_status
     *
     * @return the value of pms_product.publish_status
     *
     * @mbggenerated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.publish_status
     *
     * @param publishStatus the value for pms_product.publish_status
     *
     * @mbggenerated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.new_status
     *
     * @return the value of pms_product.new_status
     *
     * @mbggenerated
     */
    public Integer getNewStatus() {
        return newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.new_status
     *
     * @param newStatus the value for pms_product.new_status
     *
     * @mbggenerated
     */
    public void setNewStatus(Integer newStatus) {
        this.newStatus = newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.recommand_status
     *
     * @return the value of pms_product.recommand_status
     *
     * @mbggenerated
     */
    public Integer getRecommandStatus() {
        return recommandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.recommand_status
     *
     * @param recommandStatus the value for pms_product.recommand_status
     *
     * @mbggenerated
     */
    public void setRecommandStatus(Integer recommandStatus) {
        this.recommandStatus = recommandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.verify_status
     *
     * @return the value of pms_product.verify_status
     *
     * @mbggenerated
     */
    public Integer getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.verify_status
     *
     * @param verifyStatus the value for pms_product.verify_status
     *
     * @mbggenerated
     */
    public void setVerifyStatus(Integer verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.sort
     *
     * @return the value of pms_product.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.sort
     *
     * @param sort the value for pms_product.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.sale
     *
     * @return the value of pms_product.sale
     *
     * @mbggenerated
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.sale
     *
     * @param sale the value for pms_product.sale
     *
     * @mbggenerated
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.price
     *
     * @return the value of pms_product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.price
     *
     * @param price the value for pms_product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.promotion_price
     *
     * @return the value of pms_product.promotion_price
     *
     * @mbggenerated
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.promotion_price
     *
     * @param promotionPrice the value for pms_product.promotion_price
     *
     * @mbggenerated
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.gift_growth
     *
     * @return the value of pms_product.gift_growth
     *
     * @mbggenerated
     */
    public Integer getGiftGrowth() {
        return giftGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.gift_growth
     *
     * @param giftGrowth the value for pms_product.gift_growth
     *
     * @mbggenerated
     */
    public void setGiftGrowth(Integer giftGrowth) {
        this.giftGrowth = giftGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.gift_point
     *
     * @return the value of pms_product.gift_point
     *
     * @mbggenerated
     */
    public Integer getGiftPoint() {
        return giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.gift_point
     *
     * @param giftPoint the value for pms_product.gift_point
     *
     * @mbggenerated
     */
    public void setGiftPoint(Integer giftPoint) {
        this.giftPoint = giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.use_point_limit
     *
     * @return the value of pms_product.use_point_limit
     *
     * @mbggenerated
     */
    public Integer getUsePointLimit() {
        return usePointLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.use_point_limit
     *
     * @param usePointLimit the value for pms_product.use_point_limit
     *
     * @mbggenerated
     */
    public void setUsePointLimit(Integer usePointLimit) {
        this.usePointLimit = usePointLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.sub_title
     *
     * @return the value of pms_product.sub_title
     *
     * @mbggenerated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.sub_title
     *
     * @param subTitle the value for pms_product.sub_title
     *
     * @mbggenerated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.original_price
     *
     * @return the value of pms_product.original_price
     *
     * @mbggenerated
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.original_price
     *
     * @param originalPrice the value for pms_product.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.stock
     *
     * @return the value of pms_product.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.stock
     *
     * @param stock the value for pms_product.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.low_stock
     *
     * @return the value of pms_product.low_stock
     *
     * @mbggenerated
     */
    public Integer getLowStock() {
        return lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.low_stock
     *
     * @param lowStock the value for pms_product.low_stock
     *
     * @mbggenerated
     */
    public void setLowStock(Integer lowStock) {
        this.lowStock = lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.unit
     *
     * @return the value of pms_product.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.unit
     *
     * @param unit the value for pms_product.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.weight
     *
     * @return the value of pms_product.weight
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.weight
     *
     * @param weight the value for pms_product.weight
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.preview_status
     *
     * @return the value of pms_product.preview_status
     *
     * @mbggenerated
     */
    public Integer getPreviewStatus() {
        return previewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.preview_status
     *
     * @param previewStatus the value for pms_product.preview_status
     *
     * @mbggenerated
     */
    public void setPreviewStatus(Integer previewStatus) {
        this.previewStatus = previewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.service_ids
     *
     * @return the value of pms_product.service_ids
     *
     * @mbggenerated
     */
    public String getServiceIds() {
        return serviceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.service_ids
     *
     * @param serviceIds the value for pms_product.service_ids
     *
     * @mbggenerated
     */
    public void setServiceIds(String serviceIds) {
        this.serviceIds = serviceIds == null ? null : serviceIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.keywords
     *
     * @return the value of pms_product.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.keywords
     *
     * @param keywords the value for pms_product.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.note
     *
     * @return the value of pms_product.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.note
     *
     * @param note the value for pms_product.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.album_pics
     *
     * @return the value of pms_product.album_pics
     *
     * @mbggenerated
     */
    public String getAlbumPics() {
        return albumPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.album_pics
     *
     * @param albumPics the value for pms_product.album_pics
     *
     * @mbggenerated
     */
    public void setAlbumPics(String albumPics) {
        this.albumPics = albumPics == null ? null : albumPics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.detail_title
     *
     * @return the value of pms_product.detail_title
     *
     * @mbggenerated
     */
    public String getDetailTitle() {
        return detailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.detail_title
     *
     * @param detailTitle the value for pms_product.detail_title
     *
     * @mbggenerated
     */
    public void setDetailTitle(String detailTitle) {
        this.detailTitle = detailTitle == null ? null : detailTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.promotion_start_time
     *
     * @return the value of pms_product.promotion_start_time
     *
     * @mbggenerated
     */
    public Date getPromotionStartTime() {
        return promotionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.promotion_start_time
     *
     * @param promotionStartTime the value for pms_product.promotion_start_time
     *
     * @mbggenerated
     */
    public void setPromotionStartTime(Date promotionStartTime) {
        this.promotionStartTime = promotionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.promotion_end_time
     *
     * @return the value of pms_product.promotion_end_time
     *
     * @mbggenerated
     */
    public Date getPromotionEndTime() {
        return promotionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.promotion_end_time
     *
     * @param promotionEndTime the value for pms_product.promotion_end_time
     *
     * @mbggenerated
     */
    public void setPromotionEndTime(Date promotionEndTime) {
        this.promotionEndTime = promotionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.promotion_per_limit
     *
     * @return the value of pms_product.promotion_per_limit
     *
     * @mbggenerated
     */
    public Integer getPromotionPerLimit() {
        return promotionPerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.promotion_per_limit
     *
     * @param promotionPerLimit the value for pms_product.promotion_per_limit
     *
     * @mbggenerated
     */
    public void setPromotionPerLimit(Integer promotionPerLimit) {
        this.promotionPerLimit = promotionPerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.promotion_type
     *
     * @return the value of pms_product.promotion_type
     *
     * @mbggenerated
     */
    public Integer getPromotionType() {
        return promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.promotion_type
     *
     * @param promotionType the value for pms_product.promotion_type
     *
     * @mbggenerated
     */
    public void setPromotionType(Integer promotionType) {
        this.promotionType = promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.brand_name
     *
     * @return the value of pms_product.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.brand_name
     *
     * @param brandName the value for pms_product.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.product_category_name
     *
     * @return the value of pms_product.product_category_name
     *
     * @mbggenerated
     */
    public String getProductCategoryName() {
        return productCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.product_category_name
     *
     * @param productCategoryName the value for pms_product.product_category_name
     *
     * @mbggenerated
     */
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName == null ? null : productCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.description
     *
     * @return the value of pms_product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.description
     *
     * @param description the value for pms_product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.detail_desc
     *
     * @return the value of pms_product.detail_desc
     *
     * @mbggenerated
     */
    public String getDetailDesc() {
        return detailDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.detail_desc
     *
     * @param detailDesc the value for pms_product.detail_desc
     *
     * @mbggenerated
     */
    public void setDetailDesc(String detailDesc) {
        this.detailDesc = detailDesc == null ? null : detailDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.detail_html
     *
     * @return the value of pms_product.detail_html
     *
     * @mbggenerated
     */
    public String getDetailHtml() {
        return detailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.detail_html
     *
     * @param detailHtml the value for pms_product.detail_html
     *
     * @mbggenerated
     */
    public void setDetailHtml(String detailHtml) {
        this.detailHtml = detailHtml == null ? null : detailHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.detail_mobile_html
     *
     * @return the value of pms_product.detail_mobile_html
     *
     * @mbggenerated
     */
    public String getDetailMobileHtml() {
        return detailMobileHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.detail_mobile_html
     *
     * @param detailMobileHtml the value for pms_product.detail_mobile_html
     *
     * @mbggenerated
     */
    public void setDetailMobileHtml(String detailMobileHtml) {
        this.detailMobileHtml = detailMobileHtml == null ? null : detailMobileHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brandId=").append(brandId);
        sb.append(", productCategoryId=").append(productCategoryId);
        sb.append(", feightTemplateId=").append(feightTemplateId);
        sb.append(", productAttributeCategoryId=").append(productAttributeCategoryId);
        sb.append(", name=").append(name);
        sb.append(", pic=").append(pic);
        sb.append(", productSn=").append(productSn);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", publishStatus=").append(publishStatus);
        sb.append(", newStatus=").append(newStatus);
        sb.append(", recommandStatus=").append(recommandStatus);
        sb.append(", verifyStatus=").append(verifyStatus);
        sb.append(", sort=").append(sort);
        sb.append(", sale=").append(sale);
        sb.append(", price=").append(price);
        sb.append(", promotionPrice=").append(promotionPrice);
        sb.append(", giftGrowth=").append(giftGrowth);
        sb.append(", giftPoint=").append(giftPoint);
        sb.append(", usePointLimit=").append(usePointLimit);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", stock=").append(stock);
        sb.append(", lowStock=").append(lowStock);
        sb.append(", unit=").append(unit);
        sb.append(", weight=").append(weight);
        sb.append(", previewStatus=").append(previewStatus);
        sb.append(", serviceIds=").append(serviceIds);
        sb.append(", keywords=").append(keywords);
        sb.append(", note=").append(note);
        sb.append(", albumPics=").append(albumPics);
        sb.append(", detailTitle=").append(detailTitle);
        sb.append(", promotionStartTime=").append(promotionStartTime);
        sb.append(", promotionEndTime=").append(promotionEndTime);
        sb.append(", promotionPerLimit=").append(promotionPerLimit);
        sb.append(", promotionType=").append(promotionType);
        sb.append(", brandName=").append(brandName);
        sb.append(", productCategoryName=").append(productCategoryName);
        sb.append(", description=").append(description);
        sb.append(", detailDesc=").append(detailDesc);
        sb.append(", detailHtml=").append(detailHtml);
        sb.append(", detailMobileHtml=").append(detailMobileHtml);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}