package com.mall.dao;

import com.mall.pojo.CmsPrefrenceArea;
import java.util.List;

public interface CmsPrefrenceAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_prefrence_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_prefrence_area
     *
     * @mbggenerated
     */
    int insert(CmsPrefrenceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_prefrence_area
     *
     * @mbggenerated
     */
    CmsPrefrenceArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_prefrence_area
     *
     * @mbggenerated
     */
    List<CmsPrefrenceArea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_prefrence_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsPrefrenceArea record);
}