package com.mall.dao;

import com.mall.pojo.CmsSubject;
import java.util.List;

public interface CmsSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int insert(CmsSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    CmsSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    List<CmsSubject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsSubject record);
}