package com.mall.dao;

import com.mall.pojo.CmsTopicComment;
import java.util.List;

public interface CmsTopicCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbggenerated
     */
    int insert(CmsTopicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbggenerated
     */
    CmsTopicComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbggenerated
     */
    List<CmsTopicComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsTopicComment record);
}