package com.mall.dao;

import com.mall.pojo.CmsTopic;
import java.util.List;

public interface CmsTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int insert(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    CmsTopic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    List<CmsTopic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsTopic record);
}