package com.mall.dao;

import com.mall.pojo.OmsOrderReturnApply;
import java.util.List;

public interface OmsOrderReturnApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int insert(OmsOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    OmsOrderReturnApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    List<OmsOrderReturnApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OmsOrderReturnApply record);
}