package com.mall.dao;

import com.mall.pojo.PmsComment;
import java.util.List;

public interface PmsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment
     *
     * @mbggenerated
     */
    int insert(PmsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment
     *
     * @mbggenerated
     */
    PmsComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment
     *
     * @mbggenerated
     */
    List<PmsComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsComment record);
}