package com.mall.dao;

import com.mall.pojo.PmsProductCategoryAttributeRelation;
import java.util.List;

public interface PmsProductCategoryAttributeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category_attribute_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category_attribute_relation
     *
     * @mbggenerated
     */
    int insert(PmsProductCategoryAttributeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category_attribute_relation
     *
     * @mbggenerated
     */
    PmsProductCategoryAttributeRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category_attribute_relation
     *
     * @mbggenerated
     */
    List<PmsProductCategoryAttributeRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category_attribute_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsProductCategoryAttributeRelation record);
}