package com.mall.dao;

import com.mall.pojo.PmsProductAttribute;
import java.util.List;

public interface PmsProductAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute
     *
     * @mbggenerated
     */
    int insert(PmsProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute
     *
     * @mbggenerated
     */
    PmsProductAttribute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute
     *
     * @mbggenerated
     */
    List<PmsProductAttribute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsProductAttribute record);
}