package com.mall.dao;

import com.mall.pojo.PmsProductAttributeCategory;
import java.util.List;

public interface PmsProductAttributeCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute_category
     *
     * @mbggenerated
     */
    int insert(PmsProductAttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute_category
     *
     * @mbggenerated
     */
    PmsProductAttributeCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute_category
     *
     * @mbggenerated
     */
    List<PmsProductAttributeCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attribute_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsProductAttributeCategory record);
}