package com.mall.dao;

import com.mall.pojo.PmsProductOperateLog;
import java.util.List;

public interface PmsProductOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbggenerated
     */
    int insert(PmsProductOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbggenerated
     */
    PmsProductOperateLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbggenerated
     */
    List<PmsProductOperateLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsProductOperateLog record);
}