package com.mall.dao;

import com.mall.pojo.SmsHomeAdvertise;
import java.util.List;

public interface SmsHomeAdvertiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbggenerated
     */
    int insert(SmsHomeAdvertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbggenerated
     */
    SmsHomeAdvertise selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbggenerated
     */
    List<SmsHomeAdvertise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmsHomeAdvertise record);
}