package com.mall.dao;

import com.mall.pojo.UmsAdminPermissionRelation;
import java.util.List;

public interface UmsAdminPermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated
     */
    int insert(UmsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated
     */
    UmsAdminPermissionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated
     */
    List<UmsAdminPermissionRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsAdminPermissionRelation record);
}