package com.mall.dao;

import com.mall.pojo.UmsMemberLevel;
import java.util.List;

public interface UmsMemberLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated
     */
    int insert(UmsMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated
     */
    UmsMemberLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated
     */
    List<UmsMemberLevel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsMemberLevel record);
}