package com.mall.dao;

import com.mall.pojo.UmsMember;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("umsMemberMapper")
public interface UmsMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated
     */
    int insert(UmsMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated
     */
    UmsMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated
     */
    List<UmsMember> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsMember record);
}