package com.mall.dao;

import com.mall.pojo.UmsMemberProductCategoryRelation;
import java.util.List;

public interface UmsMemberProductCategoryRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_product_category_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_product_category_relation
     *
     * @mbggenerated
     */
    int insert(UmsMemberProductCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_product_category_relation
     *
     * @mbggenerated
     */
    UmsMemberProductCategoryRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_product_category_relation
     *
     * @mbggenerated
     */
    List<UmsMemberProductCategoryRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_product_category_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsMemberProductCategoryRelation record);
}