package com.mall.dao;

import com.mall.pojo.UmsMemberStatisticsInfo;
import java.util.List;

public interface UmsMemberStatisticsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbggenerated
     */
    int insert(UmsMemberStatisticsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbggenerated
     */
    UmsMemberStatisticsInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbggenerated
     */
    List<UmsMemberStatisticsInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsMemberStatisticsInfo record);
}