package com.mall.dao;

import com.mall.pojo.UmsRolePermissionRelation;
import java.util.List;

public interface UmsRolePermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission_relation
     *
     * @mbggenerated
     */
    int insert(UmsRolePermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission_relation
     *
     * @mbggenerated
     */
    UmsRolePermissionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission_relation
     *
     * @mbggenerated
     */
    List<UmsRolePermissionRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsRolePermissionRelation record);
}