spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
  jpa:
    show-sql: true
  redis:
    cluster:
      nodes: 127.0.0.1:6380,127.0.0.1:6381
    #    port: 6379
    #    host: 127.0.0.1
    #    timeout: PT1M
    lock:
      key: miaosha
    password: 123456


server:
  port: 8081
